name: Slack Notification

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'book-report')
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: random
          SLACK_USERNAME: BookRepo Bot
          SLACK_ICON_EMOJI: :books:
          SLACK_COLOR: '#36a64f'
          SLACK_TITLE: "📚 新しい読書感想文が追加されました！"
          SLACK_MESSAGE: |
            *タイトル*: ${{ github.event.pull_request.title }}
            *投稿者*: ${{ github.event.pull_request.user.login }}
            *リンク*: ${{ github.event.pull_request.html_url }}

            --------------------------------------------------
            詳細な内容はリンク先をご確認ください。
            --------------------------------------------------
            チームのナレッジとして活用しましょう！
          SLACK_FOOTER: "Saiteki Study Docs"
